# Generated by Django 4.2.17 on 2025-03-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('professor', 'Professor')], default='student', max_length=10),
        ),
    ]
