# Generated by Django 4.2.17 on 2025-03-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='university_id',
            new_name='university',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='university_id',
            new_name='university',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='university_id',
            new_name='university',
        ),
        migrations.AlterField(
            model_name='registeredsubject',
            name='student',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registeredsubject',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.CharField(max_length=255),
        ),
    ]
